parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
#                driver:   'postgresql'
#                host:     '%database_host%'
#                port:     '%database_port%'
#                dbname:   '%database_name%'
#                user:     '%database_user%'
#                password: '%database_password%'
#                charset:  UTF8
                url: '%env(resolve:DATABASE_URL)%'
            agencia:
                url: '%env(resolve:DATABASE2_URL)%'
            localidade:
                url: '%env(resolve:DATABASE3_URL)%'
            gefra:
                url: '%env(resolve:DATABASE4_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: false
        default_entity_manager: default
        entity_managers:
            gefra:
                connection: gefra
                mappings:
                    Agencia:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Gefra'
                        prefix: 'App\Entity\Gefra'
                        alias: Gefra
            agencia:
                connection: agencia
                mappings:
                    Agencia:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Agencia'
                        prefix: 'App\Entity\Agencia'
                        alias: Agencia
            locais:
                connection: localidade
                mappings:
                    Locais:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Localidade'
                        prefix: 'App\Entity\Localidade'
                        alias: Locais
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
