security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory: { memory: ~ }
        my_db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: ~
            # activate different ways to authenticate
            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
#                csrf_provider: security.csrf.token_manager
            form_login:
                provider: my_db_provider
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
            logout_on_user_change: true
#        secured_area:
#            csrf_token_generator: security.csrf.token_manager
#            # ...
#            logout:
#                path:   /logout
#                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/usuario, roles: ROLE_ADMIN }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/entrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/autenticar-via-codigo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/esqueci-senha, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
