security:
    encoders:
        App\Entity\Main\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory: { memory: ~ }
        my_db_provider:
            entity:
                class: App\Entity\Main\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            form_login:
                provider: my_db_provider
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: security_check_last_login
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true

#        secured_area:
#            csrf_token_generator: security.csrf.token_manager
#            # ...
#            logout:
#                path:   /logout
#                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/usuario, roles: ROLE_ADMIN }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/autenticacao/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/autenticar-via-codigo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/esqueci-senha, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/agencias/banco, roles: ROLE_ADMIN }
#        - { path: ^/agencias, roles: ROLE_USER }

    role_hierarchy:
        ROLE_MASTER:     ROLE_USER
        ROLE_ADMIN:      [ROLE_MASTER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPERADMIN: [ROLE_ADMIN, ROLE_MASTER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
