twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/sb-admin-form-fields.html.twig'
        - 'bootstrap_4_horizontal_layout.html.twig'
    globals:
        appversion: '%app.version%'
        apptitle: '%app.title%'
        appname: '%app.name%'
        description: '%app.description%'
        footer: '%app.footer%'
        author: '%app.author%'
        appmailsender: '%mail.address%'